---
name: PR Opened - Lint and Test Terraform Changes
run-name: Terraform Change Detected In PR ${{ github.event.number }} on ${{ github.head_ref }} - Lint and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint-tf:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Init
        run: terraform init

      - name: Init TFLint
        run: tflint --init

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Run TFLint
        run: tflint -f compact

  security-scan-tf:
    runs-on: ubuntu-latest
    needs:
      - lint-tf
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'